# Generated by Django 5.2.17 on 2026-09-12 08:40

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('households', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('normalized_name', models.CharField(editable=False, max_length=100)),
                ('aliases', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None, verbose_name='alias')),
                ('category', models.CharField(choices=[('produce', 'Frutas y verduras'), ('meat', 'Carne'), ('fish', 'Pescado y marisco'), ('dairy_eggs', 'Lácteos y huevos'), ('bakery', 'Pan y cereales'), ('pasta_rice_legumes', 'Pasta, arroz y legumbres'), ('pantry', 'Despensa'), ('spices', 'Especias y condimentos'), ('frozen', 'Congelados'), ('drinks', 'Bebidas'), ('other', 'Otros')], default='other', max_length=24, verbose_name='categoría')),
                ('default_unit', models.CharField(choices=[('g', 'g'), ('kg', 'kg'), ('ml', 'ml'), ('l', 'l'), ('tbsp', 'cucharada'), ('tsp', 'cucharadita'), ('unit', 'unidad'), ('clove', 'diente'), ('slice', 'loncha'), ('can', 'lata'), ('bunch', 'manojo'), ('pack', 'paquete'), ('pinch', 'pizca')], default='g', max_length=8, verbose_name='unidad habitual')),
                ('traits', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('gluten', 'Gluten'), ('crustaceans', 'Crustáceos'), ('egg', 'Huevo'), ('fish', 'Pescado'), ('peanut', 'Cacahuete'), ('soy', 'Soja'), ('milk', 'Leche y derivados'), ('tree_nuts', 'Frutos de cáscara'), ('celery', 'Apio'), ('mustard', 'Mostaza'), ('sesame', 'Sésamo'), ('sulphites', 'Sulfitos'), ('lupin', 'Altramuces'), ('molluscs', 'Moluscos'), ('lactose', 'Lactosa'), ('meat', 'Carne'), ('pork', 'Cerdo'), ('alcohol', 'Alcohol'), ('animal_origin', 'Origen animal')], max_length=16), blank=True, default=list, size=None, verbose_name='contiene')),
                ('trait_info_complete', models.BooleanField(default=False, help_text='Solo si se ha comprobado qué contiene. Si no, la compatibilidad será «desconocida».', verbose_name='información de alérgenos revisada')),
                ('is_processed', models.BooleanField(default=False, help_text='La composición depende de la marca: hay que revisar la etiqueta.', verbose_name='producto procesado')),
                ('source', models.CharField(choices=[('catalog', 'Catálogo'), ('manual', 'Añadido por el hogar'), ('ai', 'Propuesto por IA')], default='manual', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('household', models.ForeignKey(blank=True, help_text='Vacío = catálogo compartido.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='households.household')),
            ],
            options={
                'verbose_name': 'ingrediente',
                'verbose_name_plural': 'ingredientes',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('household', 'normalized_name'), name='unique_ingredient_name', nulls_distinct=False)],
            },
        ),
    ]
