# Generated by Django 5.2.17 on 2026-09-12 10:42

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_seed_catalog'),
        ('households', '0002_invitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('ml', 'ml'), ('unit', 'unidad'), ('clove', 'diente'), ('slice', 'loncha'), ('can', 'lata'), ('bunch', 'manojo'), ('pack', 'paquete'), ('pinch', 'pizca')], max_length=8, verbose_name='unidad')),
                ('grams', models.DecimalField(decimal_places=3, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.001')), django.core.validators.MaxValueValidator(Decimal('5000'))], verbose_name='peso en gramos')),
                ('note', models.CharField(blank=True, max_length=80, verbose_name='nota')),
                ('household', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_conversions', to='households.household')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to='foods.ingredient')),
            ],
            options={
                'verbose_name': 'equivalencia de peso',
                'verbose_name_plural': 'equivalencias de peso',
                'ordering': ['unit'],
                'constraints': [models.UniqueConstraint(fields=('ingredient', 'household', 'unit'), name='unique_unit_conversion', nulls_distinct=False), models.CheckConstraint(condition=models.Q(('grams__gt', 0)), name='unit_conversion_positive')],
            },
        ),
    ]
