# Generated by Django 5.2.17 on 2026-09-12 15:52

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0006_seed_legumes'),
        ('households', '0003_invitation_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traits', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('gluten', 'Gluten'), ('crustaceans', 'Crustáceos'), ('egg', 'Huevo'), ('fish', 'Pescado'), ('peanut', 'Cacahuete'), ('soy', 'Soja'), ('milk', 'Leche y derivados'), ('tree_nuts', 'Frutos de cáscara'), ('celery', 'Apio'), ('mustard', 'Mostaza'), ('sesame', 'Sésamo'), ('sulphites', 'Sulfitos'), ('lupin', 'Altramuces'), ('molluscs', 'Moluscos'), ('legumes', 'Legumbres'), ('lactose', 'Lactosa'), ('meat', 'Carne'), ('pork', 'Cerdo'), ('alcohol', 'Alcohol'), ('animal_origin', 'Origen animal')], max_length=16), blank=True, default=list, size=None, verbose_name='contiene según la etiqueta')),
                ('note', models.CharField(blank=True, max_length=120, verbose_name='marca o nota')),
                ('reviewed_at', models.DateTimeField(auto_now=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_reviews', to='households.household')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='household_reviews', to='foods.ingredient')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'revisión de etiqueta',
                'verbose_name_plural': 'revisiones de etiqueta',
                'constraints': [models.UniqueConstraint(fields=('household', 'ingredient'), name='unique_ingredient_review')],
            },
        ),
    ]
