# Generated by Django 5.2.17 on 2026-09-12 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('households', '0003_invitation_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(max_length=80)),
                ('livemode', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('stripe_subscription_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('status', models.CharField(blank=True, max_length=24, verbose_name='estado')),
                ('price_id', models.CharField(blank=True, max_length=64)),
                ('interval', models.CharField(blank=True, max_length=8, verbose_name='periodo')),
                ('current_period_end', models.DateTimeField(blank=True, null=True, verbose_name='renovación')),
                ('cancel_at_period_end', models.BooleanField(default=False, verbose_name='se cancela al final del periodo')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('household', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='households.household')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'suscripción',
                'verbose_name_plural': 'suscripciones',
            },
        ),
    ]
