# Generated by Django 5.2.17 on 2026-09-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='stripe_event_at',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
