# Generated by Django 5.2.17 on 2026-09-12 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=20, verbose_name='tipo')),
                ('recipient', models.EmailField(blank=True, max_length=254, verbose_name='destinatario')),
                ('message_id', models.CharField(blank=True, max_length=255)),
                ('event_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('reject_reason', models.CharField(blank=True, max_length=20, verbose_name='motivo')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='detalle')),
                ('esp_name', models.CharField(blank=True, max_length=30, verbose_name='proveedor')),
                ('occurred_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha del evento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'evento de correo',
                'verbose_name_plural': 'eventos de correo',
                'ordering': ['-created_at'],
            },
        ),
    ]
