# Generated by Django 5.2.17 on 2026-09-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_email_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThrottleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['key', 'created_at'], name='core_thrott_key_e11f5c_idx')],
            },
        ),
    ]
