# Generated by Django 5.2.17 on 2026-09-12 08:40

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foods', '0001_initial'),
        ('households', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=60, verbose_name='nombre o alias')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='fecha de nacimiento')),
                ('portion_factor', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='1 = ración estándar de adulto; 0,5 = media ración.', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.10')), django.core.validators.MaxValueValidator(Decimal('5.00'))], verbose_name='tamaño de ración')),
                ('height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('30')), django.core.validators.MaxValueValidator(Decimal('250'))], verbose_name='altura (cm)')),
                ('notes', models.TextField(blank=True, help_text='Texto libre. No se comprueba automáticamente: no lo uses para alergias.', verbose_name='otras observaciones')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diners', to='households.household')),
                ('linked_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diner_profiles', to=settings.AUTH_USER_MODEL, verbose_name='cuenta vinculada')),
            ],
            options={
                'verbose_name': 'comensal',
                'verbose_name_plural': 'comensales',
                'ordering': ['alias'],
            },
        ),
        migrations.CreateModel(
            name='WeightMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measured_on', models.DateField(verbose_name='fecha')),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('1')), django.core.validators.MaxValueValidator(Decimal('400'))], verbose_name='peso (kg)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weights', to='diners.diner')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-measured_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendancePattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('meal_type', models.CharField(choices=[('breakfast', 'Desayuno'), ('lunch', 'Comida'), ('snack', 'Merienda'), ('dinner', 'Cena')], max_length=16)),
                ('attends', models.BooleanField(default=True)),
                ('diner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_patterns', to='diners.diner')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('diner', 'weekday', 'meal_type'), name='unique_attendance_pattern')],
            },
        ),
        migrations.CreateModel(
            name='DinerPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('dislike', 'No le gusta'), ('like', 'Le gusta')], max_length=8, verbose_name='tipo')),
                ('text', models.CharField(blank=True, help_text='Por ejemplo: «platos de cuchara».', max_length=80, verbose_name='detalle')),
                ('diner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='diners.diner')),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foods.ingredient')),
            ],
            options={
                'verbose_name': 'preferencia',
                'verbose_name_plural': 'preferencias',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('text', ''), _negated=True), ('ingredient__isnull', False), _connector='OR'), name='preference_has_target')],
            },
        ),
        migrations.CreateModel(
            name='DinerRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('allergy', 'Alergia'), ('intolerance', 'Intolerancia'), ('diet', 'Dieta o creencia'), ('other', 'Otra restricción')], max_length=12, verbose_name='tipo')),
                ('trait', models.CharField(blank=True, choices=[('gluten', 'Gluten'), ('crustaceans', 'Crustáceos'), ('egg', 'Huevo'), ('fish', 'Pescado'), ('peanut', 'Cacahuete'), ('soy', 'Soja'), ('milk', 'Leche y derivados'), ('tree_nuts', 'Frutos de cáscara'), ('celery', 'Apio'), ('mustard', 'Mostaza'), ('sesame', 'Sésamo'), ('sulphites', 'Sulfitos'), ('lupin', 'Altramuces'), ('molluscs', 'Moluscos'), ('lactose', 'Lactosa'), ('meat', 'Carne'), ('pork', 'Cerdo'), ('alcohol', 'Alcohol'), ('animal_origin', 'Origen animal')], max_length=16, verbose_name='rasgo')),
                ('label', models.CharField(blank=True, max_length=80, verbose_name='descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restrictions', to='diners.diner')),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foods.ingredient', verbose_name='ingrediente concreto')),
            ],
            options={
                'verbose_name': 'restricción',
                'verbose_name_plural': 'restricciones',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('trait', ''), _negated=True), ('ingredient__isnull', False), _connector='OR'), name='restriction_has_target')],
            },
        ),
        migrations.CreateModel(
            name='HealthDataAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_access', to='diners.diner')),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('diner', 'user'), name='unique_health_access')],
            },
        ),
    ]
