# Generated by Django 5.2.17 on 2026-09-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinerrestriction',
            name='trait',
            field=models.CharField(blank=True, choices=[('gluten', 'Gluten'), ('crustaceans', 'Crustáceos'), ('egg', 'Huevo'), ('fish', 'Pescado'), ('peanut', 'Cacahuete'), ('soy', 'Soja'), ('milk', 'Leche y derivados'), ('tree_nuts', 'Frutos de cáscara'), ('celery', 'Apio'), ('mustard', 'Mostaza'), ('sesame', 'Sésamo'), ('sulphites', 'Sulfitos'), ('lupin', 'Altramuces'), ('molluscs', 'Moluscos'), ('legumes', 'Legumbres'), ('lactose', 'Lactosa'), ('meat', 'Carne'), ('pork', 'Cerdo'), ('alcohol', 'Alcohol'), ('animal_origin', 'Origen animal')], max_length=16, verbose_name='rasgo'),
        ),
    ]
