# Generated by Django 5.2.17 on 2026-09-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diners', '0002_legumes_trait'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinerrestriction',
            name='kind',
            field=models.CharField(choices=[('allergy', 'Alergia'), ('intolerance', 'Intolerancia'), ('diet', 'Dieta o creencia'), ('diabetes', 'Diabetes'), ('other', 'Otra restricción')], max_length=12, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='dinerrestriction',
            name='trait',
            field=models.CharField(blank=True, choices=[('gluten', 'Gluten'), ('crustaceans', 'Crustáceos'), ('egg', 'Huevo'), ('fish', 'Pescado'), ('peanut', 'Cacahuete'), ('soy', 'Soja'), ('milk', 'Leche y derivados'), ('tree_nuts', 'Frutos de cáscara'), ('celery', 'Apio'), ('mustard', 'Mostaza'), ('sesame', 'Sésamo'), ('sulphites', 'Sulfitos'), ('lupin', 'Altramuces'), ('molluscs', 'Moluscos'), ('legumes', 'Legumbres'), ('lactose', 'Lactosa'), ('meat', 'Carne'), ('pork', 'Cerdo'), ('alcohol', 'Alcohol'), ('animal_origin', 'Origen animal'), ('added_sugar', 'Azúcares añadidos')], max_length=16, verbose_name='rasgo'),
        ),
    ]
