# Generated by Django 5.2.17 on 2026-09-13 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('households', '0003_invitation_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=1000, unique=True)),
                ('p256dh', models.CharField(max_length=200)),
                ('auth', models.CharField(max_length=100)),
                ('user_agent', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('failures', models.PositiveSmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'dispositivo con notificaciones',
                'verbose_name_plural': 'dispositivos con notificaciones',
            },
        ),
        migrations.CreateModel(
            name='ReminderPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tomorrow', models.BooleanField(default=True, help_text='Con lo que hay que dejar preparado la víspera: poner en remojo, descongelar…', verbose_name='Avisarme de lo que hay mañana')),
                ('hour', models.PositiveSmallIntegerField(choices=[(16, '16:00'), (17, '17:00'), (18, '18:00'), (19, '19:00'), (20, '20:00'), (21, '21:00'), (22, '22:00')], default=20, verbose_name='Hora del aviso')),
                ('week', models.BooleanField(default=True, verbose_name='Avisarme el domingo si la semana siguiente está sin planificar')),
                ('last_tomorrow_on', models.DateField(blank=True, null=True)),
                ('last_week_on', models.DateField(blank=True, null=True)),
                ('membership', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='households.membership')),
            ],
            options={
                'verbose_name': 'preferencia de recordatorios',
                'verbose_name_plural': 'preferencias de recordatorios',
            },
        ),
    ]
