# Generated by Django 5.2.17 on 2026-09-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='health_consent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='consentimiento de datos de salud'),
        ),
        migrations.AddField(
            model_name='user',
            name='legal_version',
            field=models.CharField(blank=True, max_length=20, verbose_name='versión de los textos legales aceptada'),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='condiciones aceptadas'),
        ),
    ]
