# Generated by Django 5.2.17 on 2026-09-12 08:40

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diners', '0001_initial'),
        ('foods', '0001_initial'),
        ('households', '0001_initial'),
        ('recipes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='fecha')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Desayuno'), ('lunch', 'Comida'), ('snack', 'Merienda'), ('dinner', 'Cena')], max_length=16, verbose_name='tipo')),
                ('mode', models.CharField(choices=[('cook', 'Cocinar en casa'), ('eat_out', 'Comer fuera'), ('order', 'Pedir comida'), ('leftovers', 'Aprovechar sobras'), ('free', 'Libre'), ('pending', 'Pendiente')], default='pending', max_length=10, verbose_name='modalidad')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('locked', models.BooleanField(default=False, help_text='Las regeneraciones no modifican una comida protegida.', verbose_name='protegida')),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('generated', 'Generada'), ('ai', 'Propuesta de IA')], default='manual', max_length=10)),
                ('version', models.PositiveIntegerField(default=1)),
                ('safety_status', models.CharField(choices=[('ok', 'Compatible según los datos'), ('unknown', 'Requiere revisión'), ('conflict', 'Incompatible'), ('na', 'Sin recetas')], default='na', max_length=10)),
                ('safety_issues', models.JSONField(blank=True, default=list)),
                ('safety_checked_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.CharField(choices=[('pending', 'Sin registrar'), ('as_planned', 'Como estaba previsto'), ('changed', 'Se comió otra cosa'), ('skipped', 'No se hizo')], default='pending', max_length=12, verbose_name='qué se comió')),
                ('outcome_notes', models.CharField(blank=True, max_length=200, verbose_name='detalle de lo consumido')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='households.household')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'comida',
                'verbose_name_plural': 'comidas',
                'ordering': ['date', 'meal_type'],
            },
        ),
        migrations.CreateModel(
            name='MealAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(blank=True, max_length=60, verbose_name='invitado')),
                ('guest_traits', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('gluten', 'Gluten'), ('crustaceans', 'Crustáceos'), ('egg', 'Huevo'), ('fish', 'Pescado'), ('peanut', 'Cacahuete'), ('soy', 'Soja'), ('milk', 'Leche y derivados'), ('tree_nuts', 'Frutos de cáscara'), ('celery', 'Apio'), ('mustard', 'Mostaza'), ('sesame', 'Sésamo'), ('sulphites', 'Sulfitos'), ('lupin', 'Altramuces'), ('molluscs', 'Moluscos'), ('lactose', 'Lactosa'), ('meat', 'Carne'), ('pork', 'Cerdo'), ('alcohol', 'Alcohol'), ('animal_origin', 'Origen animal')], max_length=16), blank=True, default=list, size=None, verbose_name='restricciones del invitado')),
                ('guest_notes', models.CharField(blank=True, max_length=120, verbose_name='otras restricciones del invitado')),
                ('portion', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))])),
                ('diner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diners.diner')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='planning.meal')),
            ],
        ),
        migrations.CreateModel(
            name='MealRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_version', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=120)),
                ('base_servings', models.PositiveSmallIntegerField(default=4)),
                ('servings_override', models.DecimalField(blank=True, decimal_places=2, help_text='Vacío = las raciones de los asistentes.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))], verbose_name='raciones')),
                ('prep_minutes', models.PositiveSmallIntegerField(default=0)),
                ('cook_minutes', models.PositiveSmallIntegerField(default=0)),
                ('steps', models.JSONField(blank=True, default=list)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='planning.meal')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meal_uses', to='recipes.recipe')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MealRecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('unit', models.CharField(choices=[('g', 'g'), ('kg', 'kg'), ('ml', 'ml'), ('l', 'l'), ('tbsp', 'cucharada'), ('tsp', 'cucharadita'), ('unit', 'unidad'), ('clove', 'diente'), ('slice', 'loncha'), ('can', 'lata'), ('bunch', 'manojo'), ('pack', 'paquete'), ('pinch', 'pizca')], max_length=8)),
                ('note', models.CharField(blank=True, max_length=80)),
                ('optional', models.BooleanField(default=False)),
                ('manual_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='cantidad corregida')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='foods.ingredient')),
                ('meal_recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='planning.mealrecipe')),
                ('substituted_for', models.ForeignKey(blank=True, help_text='Ingrediente original de la receta si esta línea es una sustitución.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='foods.ingredient')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RecurringRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='día')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Desayuno'), ('lunch', 'Comida'), ('snack', 'Merienda'), ('dinner', 'Cena')], max_length=16, verbose_name='comida')),
                ('mode', models.CharField(choices=[('cook', 'Cocinar en casa'), ('eat_out', 'Comer fuera'), ('order', 'Pedir comida'), ('leftovers', 'Aprovechar sobras'), ('free', 'Libre'), ('pending', 'Pendiente')], max_length=10, verbose_name='modalidad')),
                ('notes', models.CharField(blank=True, max_length=120, verbose_name='nota')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='desde')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='hasta')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_rules', to='households.household')),
            ],
            options={
                'ordering': ['weekday', 'meal_type'],
            },
        ),
        migrations.CreateModel(
            name='DateException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='fecha')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Desayuno'), ('lunch', 'Comida'), ('snack', 'Merienda'), ('dinner', 'Cena')], max_length=16, verbose_name='comida')),
                ('mode', models.CharField(blank=True, choices=[('cook', 'Cocinar en casa'), ('eat_out', 'Comer fuera'), ('order', 'Pedir comida'), ('leftovers', 'Aprovechar sobras'), ('free', 'Libre'), ('pending', 'Pendiente')], max_length=10, verbose_name='modalidad')),
                ('override_attendance', models.BooleanField(default=False, verbose_name='fijar asistentes')),
                ('notes', models.CharField(blank=True, max_length=120, verbose_name='nota')),
                ('attendees', models.ManyToManyField(blank=True, to='diners.diner', verbose_name='asistentes')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_exceptions', to='households.household')),
            ],
            options={
                'ordering': ['date', 'meal_type'],
                'constraints': [models.UniqueConstraint(fields=('household', 'date', 'meal_type'), name='unique_date_exception')],
            },
        ),
        migrations.AddConstraint(
            model_name='meal',
            constraint=models.UniqueConstraint(fields=('household', 'date', 'meal_type'), name='unique_meal_slot'),
        ),
        migrations.AddConstraint(
            model_name='mealattendee',
            constraint=models.CheckConstraint(condition=models.Q(('diner__isnull', False), models.Q(('guest_name', ''), _negated=True), _connector='OR'), name='attendee_is_someone'),
        ),
        migrations.AddConstraint(
            model_name='mealattendee',
            constraint=models.UniqueConstraint(condition=models.Q(('diner__isnull', False)), fields=('meal', 'diner'), name='unique_meal_diner'),
        ),
    ]
