# Generated by Django 5.2.17 on 2026-09-12 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='leftovers_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leftover_meals', to='planning.meal', verbose_name='sobras de'),
        ),
    ]
