# Generated by Django 5.2.17 on 2026-09-12 14:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_meal_leftovers_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealattendee',
            name='guest_traits',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('gluten', 'Gluten'), ('crustaceans', 'Crustáceos'), ('egg', 'Huevo'), ('fish', 'Pescado'), ('peanut', 'Cacahuete'), ('soy', 'Soja'), ('milk', 'Leche y derivados'), ('tree_nuts', 'Frutos de cáscara'), ('celery', 'Apio'), ('mustard', 'Mostaza'), ('sesame', 'Sésamo'), ('sulphites', 'Sulfitos'), ('lupin', 'Altramuces'), ('molluscs', 'Moluscos'), ('legumes', 'Legumbres'), ('lactose', 'Lactosa'), ('meat', 'Carne'), ('pork', 'Cerdo'), ('alcohol', 'Alcohol'), ('animal_origin', 'Origen animal')], max_length=16), blank=True, default=list, size=None, verbose_name='restricciones del invitado'),
        ),
    ]
