# Generated by Django 5.2.17 on 2026-09-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_legumes_trait'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealrecipe',
            name='eaters',
            field=models.ManyToManyField(blank=True, related_name='plates', to='planning.mealattendee', verbose_name='para quién'),
        ),
    ]
