# Generated by Django 5.2.17 on 2026-09-13 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0003_invitation_email'),
        ('planning', '0004_meal_recipe_eaters'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_feeds', to='households.household')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_feeds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'enlace de calendario',
                'verbose_name_plural': 'enlaces de calendario',
                'constraints': [models.UniqueConstraint(fields=('user', 'household'), name='unique_calendar_feed')],
            },
        ),
    ]
