# Generated by Django 5.2.17 on 2026-09-12 08:40

import core.choices
import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='nombre')),
                ('enabled_meal_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('breakfast', 'Desayuno'), ('lunch', 'Comida'), ('snack', 'Merienda'), ('dinner', 'Cena')], max_length=16), default=core.choices.default_meal_types, size=None, verbose_name='tipos de comida activos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'hogar',
                'verbose_name_plural': 'hogares',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('editor', 'Editor'), ('reader', 'Lector')], default='reader', max_length=10, verbose_name='rol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='households.household')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'miembro',
                'verbose_name_plural': 'miembros',
                'constraints': [models.UniqueConstraint(fields=('user', 'household'), name='unique_membership')],
            },
        ),
    ]
