# Generated by Django 5.2.17 on 2026-09-12 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0002_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='enviada a'),
        ),
    ]
