# Generated by Django 5.2.17 on 2026-09-12 08:40

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foods', '0001_initial'),
        ('households', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('base_servings', models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)], verbose_name='raciones base')),
                ('prep_minutes', models.PositiveSmallIntegerField(default=0, verbose_name='preparación (min)')),
                ('cook_minutes', models.PositiveSmallIntegerField(default=0, verbose_name='cocción (min)')),
                ('equipment', models.CharField(blank=True, max_length=200, verbose_name='equipamiento')),
                ('difficulty', models.CharField(choices=[('easy', 'Fácil'), ('medium', 'Media'), ('hard', 'Elaborada')], default='easy', max_length=8, verbose_name='dificultad')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=list, size=None, verbose_name='etiquetas')),
                ('origin', models.CharField(choices=[('manual', 'Manual'), ('demo', 'Demostración'), ('ai', 'Generada por IA')], default='manual', max_length=8, verbose_name='origen')),
                ('review_status', models.CharField(choices=[('reviewed', 'Revisada'), ('needs_review', 'Pendiente de revisión')], default='reviewed', max_length=16, verbose_name='estado de revisión')),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_archived', models.BooleanField(default=False, verbose_name='archivada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='households.household')),
            ],
            options={
                'verbose_name': 'receta',
                'verbose_name_plural': 'recetas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, help_text='Vacío = al gusto (no se añade a la compra).', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='cantidad')),
                ('unit', models.CharField(choices=[('g', 'g'), ('kg', 'kg'), ('ml', 'ml'), ('l', 'l'), ('tbsp', 'cucharada'), ('tsp', 'cucharadita'), ('unit', 'unidad'), ('clove', 'diente'), ('slice', 'loncha'), ('can', 'lata'), ('bunch', 'manojo'), ('pack', 'paquete'), ('pinch', 'pizca')], default='g', max_length=8, verbose_name='unidad')),
                ('note', models.CharField(blank=True, max_length=80, verbose_name='nota')),
                ('optional', models.BooleanField(default=False, verbose_name='opcional')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_uses', to='foods.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.recipe')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RecipeStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('text', models.TextField(verbose_name='paso')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='recipes.recipe')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RecipeFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='recipes.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_recipes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'recipe'), name='unique_favorite')],
            },
        ),
    ]
