# Generated by Django 5.2.17 on 2026-09-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='source_url',
            field=models.URLField(blank=True, help_text='Enlace a la página de donde viene.', max_length=500, verbose_name='receta original'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='origin',
            field=models.CharField(choices=[('manual', 'Manual'), ('demo', 'Demostración'), ('ai', 'Generada por IA'), ('imported', 'Importada de la web')], default='manual', max_length=8, verbose_name='origen'),
        ),
    ]
