# Generated by Django 5.2.17 on 2026-09-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_import'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='advance_note',
            field=models.CharField(blank=True, help_text='Por ejemplo: poner los garbanzos en remojo, sacar el pescado del congelador. Sale en el recordatorio del día anterior.', max_length=120, verbose_name='preparar la víspera'),
        ),
    ]
