# Generated by Django 5.2.17 on 2026-09-12 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('households', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=16)),
                ('model', models.CharField(blank=True, max_length=80)),
                ('operation', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('ok', 'Correcta'), ('refused', 'Rechazada por el modelo'), ('incomplete', 'Incompleta'), ('invalid', 'Esquema inválido'), ('error', 'Error del proveedor'), ('timeout', 'Tiempo agotado'), ('not_configured', 'Sin configurar')], max_length=16)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('input_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('output_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('request_id', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('household', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='households.household')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('plan_range', 'Proponer menú'), ('replace_meal', 'Reemplazar comida'), ('generate_recipe', 'Generar receta'), ('chat', 'Chat')], max_length=20)),
                ('provider', models.CharField(max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pendiente de revisar'), ('applied', 'Aplicada'), ('discarded', 'Descartada'), ('stale', 'Desactualizada')], default='pending', max_length=12)),
                ('summary', models.TextField(blank=True)),
                ('items', models.JSONField(default=list)),
                ('new_recipes', models.JSONField(blank=True, default=list)),
                ('base_versions', models.JSONField(default=dict)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('result_message', models.TextField(blank=True)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='households.household')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Tú'), ('assistant', 'Asistente')], max_length=10)),
                ('text', models.TextField()),
                ('is_error', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='households.household')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='assistant.proposal')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
