# Generated by Django 5.2.17 on 2026-09-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='operation',
            field=models.CharField(choices=[('plan_range', 'Proponer menú'), ('replace_meal', 'Reemplazar comida'), ('generate_recipe', 'Generar receta'), ('import_recipe', 'Importar receta'), ('chat', 'Chat')], max_length=20),
        ),
    ]
