# Generated by Django 5.2.17 on 2026-09-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_recipe_import'),
    ]

    operations = [
        migrations.AddField(
            model_name='airequestlog',
            name='key_source',
            field=models.CharField(choices=[('server', 'Clave del servidor'), ('device', 'Clave del dispositivo')], default='server', max_length=8),
        ),
    ]
