# Generated by Django 5.2.17 on 2026-09-12 08:40

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foods', '0001_initial'),
        ('households', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80, verbose_name='nombre')),
                ('start_date', models.DateField(verbose_name='desde')),
                ('end_date', models.DateField(verbose_name='hasta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recalculated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_lists', to='households.household')),
            ],
            options={
                'verbose_name': 'lista de compra',
                'verbose_name_plural': 'listas de compra',
                'ordering': ['-start_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=120)),
                ('name', models.CharField(max_length=100, verbose_name='artículo')),
                ('category', models.CharField(choices=[('produce', 'Frutas y verduras'), ('meat', 'Carne'), ('fish', 'Pescado y marisco'), ('dairy_eggs', 'Lácteos y huevos'), ('bakery', 'Pan y cereales'), ('pasta_rice_legumes', 'Pasta, arroz y legumbres'), ('pantry', 'Despensa'), ('spices', 'Especias y condimentos'), ('frozen', 'Congelados'), ('drinks', 'Bebidas'), ('other', 'Otros')], default='other', max_length=24, verbose_name='categoría')),
                ('unit', models.CharField(blank=True, choices=[('g', 'g'), ('kg', 'kg'), ('ml', 'ml'), ('l', 'l'), ('tbsp', 'cucharada'), ('tsp', 'cucharadita'), ('unit', 'unidad'), ('clove', 'diente'), ('slice', 'loncha'), ('can', 'lata'), ('bunch', 'manojo'), ('pack', 'paquete'), ('pinch', 'pizca')], max_length=8, verbose_name='unidad')),
                ('needed_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('purchased_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='comprado')),
                ('is_manual', models.BooleanField(default=False)),
                ('manual_note', models.CharField(blank=True, max_length=120, verbose_name='nota')),
                ('sources', models.JSONField(blank=True, default=list)),
                ('purchased_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='foods.ingredient')),
                ('purchased_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shopping.shoppinglist')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='shoppinglist',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='shopping_range_valid'),
        ),
        migrations.AddConstraint(
            model_name='shoppingitem',
            constraint=models.UniqueConstraint(condition=models.Q(('key', ''), _negated=True), fields=('shopping_list', 'key'), name='unique_item_key'),
        ),
    ]
