# Generated by Django 5.2.17 on 2026-09-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingitem',
            name='is_approximate',
            field=models.BooleanField(default=False),
        ),
    ]
