# Generated by Django 5.2.17 on 2026-09-13 11:28

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0007_ingredient_review'),
        ('households', '0003_invitation_email'),
        ('shopping', '0002_shoppingitem_is_approximate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingitem',
            name='is_staple',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='pantry_quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12),
        ),
        migrations.CreateModel(
            name='PantryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('staple', 'Siempre en casa'), ('stock', 'Tenemos una cantidad')], default='staple', max_length=10, verbose_name='cómo')),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='cantidad')),
                ('unit', models.CharField(blank=True, choices=[('g', 'g'), ('kg', 'kg'), ('ml', 'ml'), ('l', 'l'), ('tbsp', 'cucharada'), ('tsp', 'cucharadita'), ('unit', 'unidad'), ('clove', 'diente'), ('slice', 'loncha'), ('can', 'lata'), ('bunch', 'manojo'), ('pack', 'paquete'), ('pinch', 'pizca')], max_length=8, verbose_name='unidad')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pantry_items', to='households.household')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='foods.ingredient')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'artículo de la despensa',
                'verbose_name_plural': 'despensa',
                'ordering': ['ingredient__name'],
                'constraints': [models.UniqueConstraint(fields=('household', 'ingredient'), name='unique_pantry_ingredient')],
            },
        ),
    ]
