# Generated by Django 5.2.17 on 2026-09-13 18:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0007_ingredient_review'),
        ('households', '0003_invitation_email'),
        ('shopping', '0003_pantry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pantryitem',
            name='kind',
            field=models.CharField(choices=[('staple', 'Siempre en casa'), ('stock', 'Lo tenemos en casa')], default='staple', max_length=10, verbose_name='cómo'),
        ),
        migrations.CreateModel(
            name='PantryBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='cantidad')),
                ('unit', models.CharField(blank=True, choices=[('g', 'g'), ('kg', 'kg'), ('ml', 'ml'), ('l', 'l'), ('tbsp', 'cucharada'), ('tsp', 'cucharadita'), ('unit', 'unidad'), ('clove', 'diente'), ('slice', 'loncha'), ('can', 'lata'), ('bunch', 'manojo'), ('pack', 'paquete'), ('pinch', 'pizca')], max_length=8, verbose_name='unidad')),
                ('expires_on', models.DateField(blank=True, null=True, verbose_name='caduca')),
                ('bought_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='comprado')),
                ('note', models.CharField(blank=True, max_length=80, verbose_name='nota')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='gastado')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pantry_batches', to='households.household')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='foods.ingredient')),
                ('shopping_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pantry_batches', to='shopping.shoppingitem')),
            ],
            options={
                'verbose_name': 'lote de la despensa',
                'verbose_name_plural': 'lotes de la despensa',
                'ordering': [models.OrderBy(models.F('expires_on'), nulls_last=True), 'bought_on', 'id'],
            },
        ),
    ]
